// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjzqbhnkuivlbqhwahfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqenFiaG5rdWl2bGJxaHdhaGZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MjE1MDIsImV4cCI6MjA3MzQ5NzUwMn0.MmtDVjMQFQ1SaQg-bzbX6d_HbswazZt40o2CYl8mUXk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});